### ISSUE TITLE
Do not use math/rand

### ISSUE THREAD

**Issue by dominikschulz** [tsalzer/pwmake#11]
Using math/rand, especially when initialized by time.Now(), opens the generated password to very practical attacks.

Please either avoid the use of any king of linear congruential generator (PRNG) or at least put a warning in the README.

**Comment by tsalzer** [comment]
Agreed, this should definitively be replaced with `crypto/rand`.

**Comment by tsalzer** [comment]
Should be fixed with 158b26d1181f177caa7530ce9d3fcff8daf74d72.
